baseURL = "https://paulstapel.com/"
languageCode = 'en-us'
title = "Paul's Particles"

[params]
    dateFormat = "2 Jan, 2006" 
    siteNameMain = "Paul's Particles"
    siteNameMeditation = "Paul's Garden"
    siteNameRecipe = "Paul's Kitchen"
    favicon = "favicon.ico"

[taxonomies]
    category = "categories"
    
[outputs]
    home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.highlight]
    noClasses = false  # ✅ use CSS classes instead of inline styles
    style = "monokai"  # or any style, doesn’t matter if noClasses=false