baseURL = "https://paulstapel.com/"
languageCode = 'en-us'
title = "Paul's Particles"

[params]
    dateFormat = "2 Jan, 2006" 
    siteNameMain = "Paul's Particles"
    siteNameMeditation = "Paul's Garden"
    siteNameRecipe = "Paul's Kitchen"

[taxonomies]
    category = "categories"
    
[outputs]
    home = ["HTML", "RSS", "JSON"]

[pagination]
  disableAliases = false
  pagerSize = 1000
  path = 'page'