baseURL = "https://paulstapel.com/"
languageCode = 'en-us'
title = "Paul's Particles"

pagination.pagerSize = 100

[params]
    dateFormat = "2 Jan, 2006" 
    siteNameMain = "Paul's Particles"
    siteNameMeditation = "Paul's Garden"
    siteNameRecipe = "Paul's Kitchen"

[taxonomies]
    category = "categories"
    
[outputs]
    home = ["HTML", "RSS", "JSON"]
